from pydantic import BaseModel, Field


class PlannerOutput(BaseModel):
    """
    Output generated by the Planner Agent.
    This object is passed to the Topic Research Agent.
    """

    topic: str = Field(
        description="The selected topic for the next social media post."
    )

    pillar: str = Field(
        description="The content pillar selected from the content strategy."
    )

    brand_voice: str = Field(
    description="The tone in which the content should be written, such as professional, casual, friendly, persuasive, witty, or authoritative."
    )

    post_format: str = Field(
        description=(
            "The exact post format selected from the company's content strategy that best "
            "fits the planned content. Return only one format exactly as it appears in the "
            "strategy (e.g., Explainer, Story, Mini case study, Workflow breakdown, "
            "Checklist, Comparison, Myth vs Reality)."
        )
    )
