from pydantic import BaseModel, Field


class PlannerOutput(BaseModel):
    """
    Output generated by the Planner Agent.
    This object is passed to the Topic Research Agent.
    """

    topic: str = Field(
        description="The selected topic for the next social media post."
    )

    pillar: str = Field(
        description="The content pillar selected from the content strategy."
    )

    tone: str = Field(
    description="The tone in which the content should be written, such as professional, casual, friendly, persuasive, witty, or authoritative."
    )

    objective: str = Field(
        description="The objective of the post, such as Educate, Promote, Engage, Build Trust, Generate Leads, etc."
    )

    audience: str = Field(
        description="The primary target audience for the post."
    )