"""adding email notified column

Revision ID: 67eb6b47ba50
Revises: d6594401bf6a
Create Date: 2026-08-19 15:44:57.987860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67eb6b47ba50'
down_revision = 'd6594401bf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notified_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('recurring_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_content', schema=None) as batch_op:
        batch_op.drop_column('email_notified_at')

    with op.batch_alter_table('content_jobs', schema=None) as batch_op:
        batch_op.drop_column('email_notified_at')

    # ### end Alembic commands ###
