"""adding reccuring table

Revision ID: bd1a41408abd
Revises: 74e0023a3c96
Create Date: 2026-08-15 00:32:05.406541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1a41408abd'
down_revision = '74e0023a3c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_content_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_content_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_content_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_content_scheduled_at'))

    op.drop_table('recurring_content')
    # ### end Alembic commands ###
