"""Add image fields to recurring content

Revision ID: c50fb3ee68e4
Revises: 67eb6b47ba50
Create Date: 2026-09-30 18:19:38.581440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50fb3ee68e4'
down_revision = '67eb6b47ba50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_content', schema=None) as batch_op:
        batch_op.drop_column('image_status')
        batch_op.drop_column('image_path')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_prompt')

    # ### end Alembic commands ###
