"""adding 'platforms' to CompanyInfo

Revision ID: d6594401bf6a
Revises: bd1a41408abd
Create Date: 2026-08-17 18:05:02.874395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6594401bf6a'
down_revision = 'bd1a41408abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforms', sa.JSON(), nullable=True))
        batch_op.drop_column('last_scheduled_run_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scheduled_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('platforms')

    # ### end Alembic commands ###
